"""Initial schema

Revision ID: 88edc4091ff8
Revises: 
Create Date: 2026-08-21 12:33:42.992454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88edc4091ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('discount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(discount_type = 'FIXED' AND value > 0) OR (discount_type = 'PERCENTAGE' AND value > 0 AND value <= 100)", name='chk_discount_value'),
    sa.CheckConstraint("discount_type IN ('FIXED', 'PERCENTAGE')", name='chk_discount_type'),
    sa.CheckConstraint('max_discount_amount > 0', name='chk_discount_max'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menu_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dining_area',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_area_branch_id'), 'dining_area', ['branch_id'], unique=False)
    op.create_table('menu_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_price >= 0', name='chk_menu_item_price'),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_category_id'), 'menu_item', ['category_id'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_account_branch_id'), 'user_account', ['branch_id'], unique=False)
    op.create_table('table_entity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='chk_table_entity_capacity'),
    sa.ForeignKeyConstraint(['area_id'], ['dining_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'table_number', name='uq_table_entity_area_number')
    )
    op.create_index(op.f('ix_table_entity_area_id'), 'table_entity', ['area_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'NO_SHOW', 'COMPLETED')", name='chk_reservation_status'),
    sa.CheckConstraint('end_time > start_time', name='chk_reservation_time'),
    sa.CheckConstraint('guest_count > 0', name='chk_reservation_guests'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_customer_id'), 'reservation', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.create_index(op.f('ix_reservation_table_id'), 'reservation', ['table_id'], unique=False)
    op.create_table('dining_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND end_time IS NULL) OR (status = 'COMPLETED' AND end_time IS NOT NULL)", name='chk_session_end_time'),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED')", name='chk_session_status'),
    sa.CheckConstraint('guest_count > 0', name='chk_session_guests'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_session_reservation_id'), 'dining_session', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_dining_session_status'), 'dining_session', ['status'], unique=False)
    op.create_index(op.f('ix_dining_session_table_id'), 'dining_session', ['table_id'], unique=False)
    op.create_table('bill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='UNPAID', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UNPAID', 'PARTIAL', 'PAID', 'VOIDED')", name='chk_bill_status'),
    sa.CheckConstraint('subtotal >= 0', name='chk_bill_subtotal'),
    sa.CheckConstraint('tax_amount >= 0', name='chk_bill_tax'),
    sa.CheckConstraint('total_amount >= 0', name='chk_bill_total'),
    sa.ForeignKeyConstraint(['session_id'], ['dining_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_session_id'), 'bill', ['session_id'], unique=True)
    op.create_index(op.f('ix_bill_status'), 'bill', ['status'], unique=False)
    op.create_table('customer_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PLACED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PLACED', 'CONFIRMED', 'PREPARING', 'READY', 'SERVED', 'CANCELLED')", name='chk_order_status'),
    sa.ForeignKeyConstraint(['session_id'], ['dining_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_session_id'), 'customer_order', ['session_id'], unique=False)
    op.create_table('discount_application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=False),
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('authorized_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(discount_amount IS NOT NULL AND discount_percentage IS NULL) OR (discount_amount IS NULL AND discount_percentage IS NOT NULL)', name='chk_da_exclusive'),
    sa.CheckConstraint('discount_amount > 0', name='chk_da_amount'),
    sa.CheckConstraint('discount_percentage > 0 AND discount_percentage <= 100', name='chk_da_percentage'),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_application_bill_id'), 'discount_application', ['bill_id'], unique=False)
    op.create_index(op.f('ix_discount_application_discount_id'), 'discount_application', ['discount_id'], unique=False)
    op.create_table('kitchen_ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('prep_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'IN_PROGRESS', 'READY')", name='chk_kitchen_ticket_status'),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_ticket_order_id'), 'kitchen_ticket', ['order_id'], unique=True)
    op.create_table('order_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_order_item_qty'),
    sa.CheckConstraint('unit_price >= 0', name='chk_order_item_price'),
    sa.ForeignKeyConstraint(['item_id'], ['menu_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_item_id'), 'order_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('CASH', 'CARD', 'ONLINE', 'WALLET')", name='chk_payment_method'),
    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')", name='chk_payment_status'),
    sa.CheckConstraint('amount > 0', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_index(op.f('ix_payment_bill_id'), 'payment', ['bill_id'], unique=False)
    op.create_table('bill_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), sa.Computed('quantity * unit_price', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_bill_item_qty'),
    sa.CheckConstraint('unit_price >= 0', name='chk_bill_item_price'),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_ticket_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PREPARING', 'COMPLETED', 'CANCELLED')", name='chk_kt_item_status'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['kitchen_ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'order_item_id', name='uq_kitchen_ticket_item')
    )
    op.create_index(op.f('ix_kitchen_ticket_item_order_item_id'), 'kitchen_ticket_item', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kitchen_ticket_item_order_item_id'), table_name='kitchen_ticket_item')
    op.drop_table('kitchen_ticket_item')
    op.drop_table('bill_item')
    op.drop_index(op.f('ix_payment_bill_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_kitchen_ticket_order_id'), table_name='kitchen_ticket')
    op.drop_table('kitchen_ticket')
    op.drop_index(op.f('ix_discount_application_discount_id'), table_name='discount_application')
    op.drop_index(op.f('ix_discount_application_bill_id'), table_name='discount_application')
    op.drop_table('discount_application')
    op.drop_index(op.f('ix_customer_order_session_id'), table_name='customer_order')
    op.drop_table('customer_order')
    op.drop_index(op.f('ix_bill_status'), table_name='bill')
    op.drop_index(op.f('ix_bill_session_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_dining_session_table_id'), table_name='dining_session')
    op.drop_index(op.f('ix_dining_session_status'), table_name='dining_session')
    op.drop_index(op.f('ix_dining_session_reservation_id'), table_name='dining_session')
    op.drop_table('dining_session')
    op.drop_index(op.f('ix_reservation_table_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_customer_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_table_entity_area_id'), table_name='table_entity')
    op.drop_table('table_entity')
    op.drop_index(op.f('ix_user_account_branch_id'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_menu_item_category_id'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_index(op.f('ix_dining_area_branch_id'), table_name='dining_area')
    op.drop_table('dining_area')
    op.drop_table('role')
    op.drop_table('menu_category')
    op.drop_table('discount')
    op.drop_table('customer')
    op.drop_table('branch')
    # ### end Alembic commands ###
